package project2species;
import static com.mysql.cj.conf.PropertyKey.PASSWORD;


import java.awt.Color;
import java.sql.Connection; // Correct import for Connection
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import static project2species.MySQLConnection.DB_URL;
import static project2species.MySQLConnection.USER;
import java.sql.PreparedStatement;
import java.sql.SQLException;



/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Class        AddPerson.java
 * Description  A class used to both add and edit a person into the DB.
 * Course       CS 143
 * Hourse       1 hours and 12 minutes
 * Date         5/1/2021
  History Log   7/18/2018, 5/7/2020, 4/5/2021
 * @author	<i>Niko Culevski</i>
 * @version 	%1% %2%
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
public class AddSpecies extends javax.swing.JDialog
{
    // class instance variables
   private Species mySpecies = null;
    private String name;
    private String genus;
    private int population;
    private String habitat;
    private String predators;

    private String diet;
    private final Color white = Color.WHITE; // Default background color for input textfield
    private final Color pink = Color.PINK;
     // Background color for bad input textfield
    
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * Constructor  AddPerson()--default constructor
     * Description  Create an instance of the GUI form and sets icon image.
     *              Used for Add Person.
     * Date         4/5/2021
     * History Log  7/18/2018, 5/7/2020
     * @author      <i>Niko Culevski</i>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/ 
    public AddSpecies()
    {
        initComponents();
        // Center the form
        this.setLocationRelativeTo(null);        
        // Set the default button
//        this.getRootPane().setDefaultButton(addJButton);   
        // Center the form
//        addJButton.setText("Edit");
        // Set the modal to true
        setModal(true);        
    }
    
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * Constructor  AddPerson()--overloaded constructor
     * Description  Create an instance of the GUI form and sets icon image.
     *              Used for Edit Person.
     * Date         4/5/2021
     * History Log  7/18/2018, 5/7/2020
     * @author      <i>Niko Culevski</i>
     * @param       friend Person
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
public AddSpecies(Species species) {
    this(); // Call default constructor to build GUI
    mySpecies = species;
    addNameJTextField.setText(species.getName());
    addGenusJTextField.setText(species.getGenus());
    addPopulationJTextField.setText(String.valueOf(species.getPopulation()));
    addDietJTextField.setText(species.getDiet());
    addHabitatJTextField.setText(species.getHabitat());
    addPredatorsJTextField.setText(species.getPredators()); // Adding predators field

}

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * Constructor  AddPerson()--overloaded constructor
     * Description  Create an instance of the GUI form and sets icon image.
     *              Used for Edit Person.
     * Date         4/5/2021
     * History Log  7/18/2018, 5/7/2020
     * @author      <i>Niko Culevski</i>
     * @param       parent Frame
     * @param       modal  boolean
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    public AddSpecies(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();

        // Center the form
        this.setLocationRelativeTo(null);        
        // Set the default button
        this.getRootPane().setDefaultButton(addJButton);                        
    }
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * Method:      getPerson()
     * Description: Returns the person added or edited.
     * Date:        5/12/16
     * @author      Niko Culevski
     * @return      Person
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    public Species getSpecies()
    {
        return mySpecies;
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayJPanel = new javax.swing.JPanel();
        firstJLabel = new javax.swing.JLabel();
        addNameJTextField = new javax.swing.JTextField();
        lastJLabel = new javax.swing.JLabel();
        addGenusJTextField = new javax.swing.JTextField();
        ageJLabel = new javax.swing.JLabel();
        addPopulationJTextField = new javax.swing.JTextField();
        addressJLabel = new javax.swing.JLabel();
        addDietJTextField = new javax.swing.JTextField();
        cityJLabel = new javax.swing.JLabel();
        addHabitatJTextField = new javax.swing.JTextField();
        controlJPanel = new javax.swing.JPanel();
        addJButton = new javax.swing.JButton();
        quitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        addPredatorsJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addTitleJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Employee Add Form");
        setType(java.awt.Window.Type.UTILITY);

        displayJPanel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayJPanel.setLayout(new java.awt.GridLayout(7, 2, 3, 3));

        firstJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        firstJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstJLabel.setText("Name of Species:");
        displayJPanel.add(firstJLabel);

        addNameJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addNameJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        addNameJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addNameJTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addNameJTextFieldFocusLost(evt);
            }
        });
        displayJPanel.add(addNameJTextField);

        lastJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lastJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lastJLabel.setText("Genus:");
        displayJPanel.add(lastJLabel);

        addGenusJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addGenusJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        addGenusJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addGenusJTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addGenusJTextFieldFocusLost(evt);
            }
        });
        displayJPanel.add(addGenusJTextField);

        ageJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ageJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ageJLabel.setText("Population:");
        displayJPanel.add(ageJLabel);

        addPopulationJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addPopulationJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        addPopulationJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addPopulationJTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addPopulationJTextFieldFocusLost(evt);
            }
        });
        displayJPanel.add(addPopulationJTextField);

        addressJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addressJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addressJLabel.setText("Diet:");
        displayJPanel.add(addressJLabel);

        addDietJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addDietJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        displayJPanel.add(addDietJTextField);

        cityJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cityJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cityJLabel.setText("Habitat:");
        displayJPanel.add(cityJLabel);

        addHabitatJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addHabitatJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        addHabitatJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addHabitatJTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addHabitatJTextFieldFocusLost(evt);
            }
        });
        displayJPanel.add(addHabitatJTextField);

        controlJPanel.setLayout(new java.awt.GridLayout(1, 2, 3, 3));

        addJButton.setBackground(new java.awt.Color(255, 255, 204));
        addJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addJButton.setMnemonic('A');
        addJButton.setText("Add");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(addJButton);

        quitJButton.setBackground(new java.awt.Color(255, 255, 204));
        quitJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quitJButton.setMnemonic('Q');
        quitJButton.setText("Quit");
        quitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitJButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(quitJButton);

        jLabel1.setText("Predators:");

        addPredatorsJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addPredatorsJTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addPredatorsJTextFieldFocusLost(evt);
            }
        });
        addPredatorsJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPredatorsJTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Predators:");

        addTitleJLabel.setText("Add Player");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addPredatorsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(controlJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(addTitleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(displayJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(28, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(addTitleJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(addPredatorsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(54, 54, 54)
                .addComponent(controlJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addComponent(displayJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(102, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * Method       quitJButtonActionPerformed()
     * Description  Dispose the Add form. Uses the Validation class to
     *              validate input fields.
     * Date         4/26/2021
     * @param       evt java.awt.event.ActionEvent
     * @author      <i>Niko Culevski</i>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void quitJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_quitJButtonActionPerformed
    {//GEN-HEADEREND:event_quitJButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_quitJButtonActionPerformed
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * Method       addJButtonActionPerformed()
     * Description  Add new person.
     * Date         4/26/2021
     * @param       evt java.awt.event.ActionEvent
     * @author      <i>Niko Culevski</i>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addJButtonActionPerformed
    {//GEN-HEADEREND:event_addJButtonActionPerformed

        
        
        String message = "Species not added.";
Connection conn = null;
PreparedStatement pstmt = null;

// Assuming these variables are retrieved from form inputs or another source
String name = addNameJTextField.getText();
String genus = addGenusJTextField.getText();
int population = Integer.parseInt(addPopulationJTextField.getText());
String diet = addDietJTextField.getText();
String habitat = addHabitatJTextField.getText();
String predators = addPredatorsJTextField.getText();

try {
    // Debug print statements to verify values
    System.out.println("Name: " + name);
    System.out.println("Genus: " + genus);
    System.out.println("Population: " + population);
    System.out.println("Diet: " + diet);
    System.out.println("Habitat: " + habitat);
    System.out.println("Predators: " + predators);

    // Initialize database connection
    conn = DriverManager.getConnection(MySQLConnection.DB_URL, MySQLConnection.USER, MySQLConnection.PASS);

    // Prepare SQL statement
    String sql = "INSERT INTO SpeciesTable (name, genus, population, diet, habitat, predators) VALUES (?, ?, ?, ?, ?, ?)";
    pstmt = conn.prepareStatement(sql);
    pstmt.setString(1, name);
    pstmt.setString(2, genus);
    pstmt.setInt(3, population);
    pstmt.setString(4, diet);
    pstmt.setString(5, habitat);
    pstmt.setString(6, predators);

    // Execute update
    int affectedRows = pstmt.executeUpdate();
    if (affectedRows > 0) {
        message = "Species added successfully!";
    }

    // Close form if successful
    this.dispose();
} catch (SQLException exp) {
    JOptionPane.showMessageDialog(null, message, "Database Error", JOptionPane.ERROR_MESSAGE);
    exp.printStackTrace();
} finally {
    try {
        if (pstmt != null) pstmt.close();
        if (conn != null) conn.close();
    } catch (SQLException exp) {
        exp.printStackTrace();
    }
}

        
        
        
 
//  
//   String message = "Species not added.";
//Connection conn = null;
//PreparedStatement pstmt = null;
//try {
//    // Validate and retrieve data as previously shown...
//
//    // Initialize database connection
//    conn = DriverManager.getConnection(MySQLConnection.DB_URL, MySQLConnection.USER, MySQLConnection.PASS);
//
//    // Prepare SQL statement
//    String sql = "INSERT INTO SpeciesTable (name, genus, population, diet, habitat, predators) VALUES (?, ?, ?, ?, ?, ?)";
//    pstmt = conn.prepareStatement(sql);
//    pstmt.setString(1, name);
//    pstmt.setString(2, genus);
//    pstmt.setInt(3, population);
//    pstmt.setString(4, diet);
//    pstmt.setString(5, habitat);
//    pstmt.setString(6, predators);
//
//    // Execute update
//    int affectedRows = pstmt.executeUpdate();
//    if (affectedRows > 0) {
//        message = "Species added successfully!";
//    }
//
//    // Close form if successful
//    this.dispose();
//} catch (SQLException exp) {
//    JOptionPane.showMessageDialog(null, message, "Database Error", JOptionPane.ERROR_MESSAGE);
//    exp.printStackTrace();
//} finally {
//    try {
//        if (pstmt != null) pstmt.close();
//        if (conn != null) conn.close();
//    } catch (SQLException exp) {
//        exp.printStackTrace();
//    }
//}

     
     
    }//GEN-LAST:event_addJButtonActionPerformed

   /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * Method       firstJTextFieldFocusGained()
     * Description  Highlight firstJTextFieldFocusGained as focus is gained.
     * @parem       java.awt.event.FocusEvent
     * @author      <i>Niko Culevski</i>
     * Date         4/5/2021
     * History log  8/24/2016, 4/3/2020
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void addNameJTextFieldFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_addNameJTextFieldFocusGained
    {//GEN-HEADEREND:event_addNameJTextFieldFocusGained
        addNameJTextField.selectAll();
    }//GEN-LAST:event_addNameJTextFieldFocusGained
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     *<pre>
     * Method       firstJTextFieldFocusLost()
     * Description  Change color of firstJTextField according to valid input.
     * @parem       java.awt.event.FocusEvent
     * @author      <i>Niko Culevski</i>
     * Date         4/5/2021
     * History log  8/24/2016, 4/3/2020
    *</pre>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void addNameJTextFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_addNameJTextFieldFocusLost
    {//GEN-HEADEREND:event_addNameJTextFieldFocusLost
        String input = addNameJTextField.getText();
        if(Validation.isValidName(input))
            addNameJTextField.setBackground(white);
        else
            addNameJTextField.setBackground(pink);
    }//GEN-LAST:event_addNameJTextFieldFocusLost
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * Method       lastJTextFieldFocusGained()
     * Description  Highlight lastJTextField as focus is gained.
     * @parem       java.awt.event.FocusEvent
     * @author      <i>Niko Culevski</i>
     * Date         4/5/2021
     * History log  8/24/2016, 4/3/2020
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void addGenusJTextFieldFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_addGenusJTextFieldFocusGained
    {//GEN-HEADEREND:event_addGenusJTextFieldFocusGained
        addGenusJTextField.selectAll();
    }//GEN-LAST:event_addGenusJTextFieldFocusGained
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * Method       lastJTextFieldFocusLost()
     * Description  Change color of lastJTextField according to valid input.
     * @parem       java.awt.event.FocusEvent
     * @author      <i>Niko Culevski</i>
     * Date         4/5/2021
     * History log  8/24/2016, 4/3/2020
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void addGenusJTextFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_addGenusJTextFieldFocusLost
    {//GEN-HEADEREND:event_addGenusJTextFieldFocusLost
        String input = addGenusJTextField.getText();
        if(Validation.isValidName(input))
            addGenusJTextField.setBackground(white);
        else
            addGenusJTextField.setBackground(pink);
    }//GEN-LAST:event_addGenusJTextFieldFocusLost
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * Method       ageJTextFieldFocusGained()
     * Description  Highlight ageJTextField as focus is gained.
     * @parem       java.awt.event.FocusEvent
     * @author      <i>Niko Culevski</i>
     * Date         4/5/2021
     * History log  8/24/2016, 4/3/2020
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void addPopulationJTextFieldFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_addPopulationJTextFieldFocusGained
    {//GEN-HEADEREND:event_addPopulationJTextFieldFocusGained
        addPopulationJTextField.selectAll();
    }//GEN-LAST:event_addPopulationJTextFieldFocusGained
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * Method       ageJTextFieldFocusLost()
     * Description  Change color of lastJTextField according to valid input.
     * @parem       java.awt.event.FocusEvent
     * @author      <i>Niko Culevski</i>
     * Date         4/5/2021
     * History log  8/24/2016, 4/3/2020
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void addPopulationJTextFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_addPopulationJTextFieldFocusLost
    {//GEN-HEADEREND:event_addPopulationJTextFieldFocusLost
        String input = addPopulationJTextField.getText();
        if(Validation.isInteger(input, 5, 140))     //valid age: [5,140]
            addPopulationJTextField.setBackground(white);
        else
            addPopulationJTextField.setBackground(pink);
    }//GEN-LAST:event_addPopulationJTextFieldFocusLost
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * Method       cityJTextFieldFocusGained()
     * Description  Highlight cityJTextField as focus is gained.
     * @parem       java.awt.event.FocusEvent
     * @author      <i>Niko Culevski</i>
     * Date         4/5/2021
     * History log  8/24/2016, 4/3/2020
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void addHabitatJTextFieldFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_addHabitatJTextFieldFocusGained
    {//GEN-HEADEREND:event_addHabitatJTextFieldFocusGained
        addHabitatJTextField.selectAll();
    }//GEN-LAST:event_addHabitatJTextFieldFocusGained
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * Method       cityJTextFieldFocusLost()
     * Description  Change color of cityJTextField according to valid input.
     * @parem       java.awt.event.FocusEvent
     * @author      <i>Niko Culevski</i>
     * Date         4/5/2021
     * History log  8/24/2016, 4/3/2020
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void addHabitatJTextFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_addHabitatJTextFieldFocusLost
    {//GEN-HEADEREND:event_addHabitatJTextFieldFocusLost
        String input = addHabitatJTextField.getText();
        if(Validation.isValidName(input))
            addHabitatJTextField.setBackground(white);
        else
            addHabitatJTextField.setBackground(pink);
    }//GEN-LAST:event_addHabitatJTextFieldFocusLost

    private void addPredatorsJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPredatorsJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPredatorsJTextFieldActionPerformed

    private void addPredatorsJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addPredatorsJTextFieldFocusGained
        // TODO add your handling code here:
            addPredatorsJTextField.selectAll();

    }//GEN-LAST:event_addPredatorsJTextFieldFocusGained

    private void addPredatorsJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addPredatorsJTextFieldFocusLost
        // TODO add your handling code here:
            String input = addPredatorsJTextField.getText();
    if (Validation.isValidName(input))
        addPredatorsJTextField.setBackground(white);
    else
        addPredatorsJTextField.setBackground(pink);
    }//GEN-LAST:event_addPredatorsJTextFieldFocusLost

    
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Method       predatorsJTextFieldFocusGained()
 * Description  Highlight predatorsJTextField as focus is gained.
 * @param       java.awt.event.FocusEvent
 * @author      <i>Niko Culevski</i>
 * Date         4/5/2021
 * History log  8/24/2016, 4/3/2020
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
                                          

/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Method       predatorsJTextFieldFocusLost()
 * Description  Change color of predatorsJTextField according to valid input.
 * @param       java.awt.event.FocusEvent
 * @author      <i>Niko Culevski</i>
 * Date         4/5/2021
 * History log  8/24/2016, 4/3/2020
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addDietJTextField;
    private javax.swing.JTextField addGenusJTextField;
    private javax.swing.JTextField addHabitatJTextField;
    private javax.swing.JButton addJButton;
    private javax.swing.JTextField addNameJTextField;
    private javax.swing.JTextField addPopulationJTextField;
    private javax.swing.JTextField addPredatorsJTextField;
    private javax.swing.JLabel addTitleJLabel;
    private javax.swing.JLabel addressJLabel;
    private javax.swing.JLabel ageJLabel;
    private javax.swing.JLabel cityJLabel;
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JPanel displayJPanel;
    private javax.swing.JLabel firstJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lastJLabel;
    private javax.swing.JButton quitJButton;
    // End of variables declaration//GEN-END:variables
}
